### ISSUE TITLE
When Downloaded, index.html Doesn't Highlight Vertices on Hover

### ISSUE THREAD

**Issue by powderblock** [codrops/DecorativeBackgrounds#1]
I downloaded the repo and opened index.html in Chrome.

However, the verts don't see to be interactive like they are in the demo.

Do I need to configure something on my end?

**Comment by powderblock** [comment]
<img width="1280" alt="screen shot 2018-06-27 at 9 03 22 pm" src="https://user-images.githubusercontent.com/1458607/42007360-a850ae10-7a4d-11e8-8cba-9e5750354499.png">

It's almost as if the frame is not capturing the mouse?

I'm not familiar with WebGL, so sorry if this is a silly question!

**Comment by powderblock** [comment]
Also tested this on Windows with Chrome.

Same effect.

**Comment by powderblock** [comment]
Interestingly enough, Microsoft Edge on Windows works just fine! Odd. No changes to code.

Must be a different renderer or something on the WebGL side...

**Comment by mmccall0813** [comment]
I'm getting the same thing on my Chromebook

**Comment by botelho** [comment]
The demos need to be run on a server environment.

**Comment by powderblock** [comment]
Confirmed. Deploying to S3 + EC2 **resolved** this issue.

Closing.
